// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;

namespace SpeakOut.Entities.Models
{
    public partial class AspNetUsers 

    {
        public AspNetUsers()
        {
           
        }

        [Key]
        public Guid Id { get; set; }
       
        [StringLength(50)]
        public string Civility { get; set; }
        [StringLength(256)]
        public string Email { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateOfBirth { get; set; }

        [Column("gender")]
        [StringLength(50)]
        public string Gender { get; set; }

        /* [Column("gender")]
        
        */
        public bool IsActive { get; set; }
        public int? PhoneNumber { get; set; }
        public bool? IsValid { get; set; }
        [StringLength(50)]
        public string Personnality { get; set; }
        //[StringLength(256)]
        /*public string UserName { get; set; }*/
        [StringLength(50)]
        public string UserProviderId { get; set; }
        [StringLength(256)]
        public string NormalizedUserName { get; set; }
        [StringLength(256)]
        public string NormalizedEmail { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string ConcurrencyStamp { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public DateTimeOffset? LockoutEnd { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserType { get; set; }
        [StringLength(50)]
        public string Adresse { get; set; }
        [StringLength(50)]
        public string city { get; set; }
        [StringLength(50)]
        public string country { get; set; }
        [StringLength(50)]
        public string AboutMe { get; set; }

        [StringLength(500)]
        public string photoUrl { get; set; }
        [StringLength(50)]
        public string firstName { get; set; }
        [StringLength(50)]
        public string lastName { get; set; }

       
    }

}